# This is a basic workflow to help you get started with Actions

name: Hello World

# Controls when the workflow will run
on:
 
  push:
    branches: [ "main" ]
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 
  hello-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
 

      # Runs a single command using the runners shell
      - name: Echo text
        run: echo "Hello, world!"


